enum Action
{
    CONFIGURATION = "config",
    AUTH = "auth",
    UPDATE_USER = "update-user",
    RTC_OFFER = "rtc-offer",
    RTC_ANSWER = "rtc-answer",
    RTC_ICE = "rtc-ice",
    CREATE_VIDEO_SESSION = 'create-video-session',
    DELETE_VIDEO_SESSION = 'delete-video-session',
    ACTIVE_VIDEO_SESSION = "active-video-session",
    VIDEO_SESSIONS_LIST = "video-sessions-list",
    COUNTRIES_LIST = "countries-list",
    VIDEO_SESSION_DETAILS = "video-session-details",
    VIDEO_SESSION_UPDATED = "video-session-updated",
    JOIN_VIDEO_SESSION = "join-video-session",
    LEAVE_VIDEO_SESSION = "leave-video-session",
    HIGHLIGHT_MEMBERS = "highlight-members",
    ERROR_MESSAGE = "error-message",
    START_TALK = "start-talk",
    END_TALK = "end-talk",
    RATE_TALK = "rate-talk",
    TALK_RESULT = "talk-result",
    LEAVE_TALK = "leave-talk",
    RESTART_SERVER = "restart-server",
    LOGS = "logs",
    NOTIFICATIONS_LIST = "notifications-list",
    NEW_NOTIFICATION = "new-notification",
    SEE_NOTIFICATION = "see-notification",
    CONVERSATIONS_LIST = "conversations-list",
    SEND_MESSAGE = "send-message",
    INCOMING_MESSAGE = "incoming-message",
    MESSAGES_LIST = "messages-list",
    SEE_MESSAGE = "see-message",
    CONVERSATION_UPDATE = "conversation-update",
}


export default Action